# Generated by Django 4.0.4 on 2022-06-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-02-18'),
            preserve_default=False,
        ),
    ]
